name: Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL of artifact to be downloaded"
        required: true
        default: ""
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:

      - name: Fetching.....
        run: |
          curl -L "${{ inputs.url }}" -o boot.img
          ls -lh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.4.1
        with:
          tag_name: "download-$(date +'%Y%m%d-%H%M%S')"
          name: "source = ${{ inputs.url }}"
          files: |
            ${{ github.workspace }}/boot.img
